# This file was generated by GoReleaser. DO NOT EDIT.
cask "fmtkit" do
  version "0.5.7"

  on_macos do
    on_intel do
      sha256 "ed78a8f2f2044e567583a31bc8ebbf11d48f894c8658804fe97a10e8ab022064"
      url "https://github.com/oullin/fmtkit/releases/download/v#{version}/fmtkit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c75eaf4d02cd5ddd7d4ac92c730d5ac4c008f2c40f272d3e4439da6a824aa07b"
      url "https://github.com/oullin/fmtkit/releases/download/v#{version}/fmtkit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c491c1ce084c9272739057c7be7ff71cc00ad3b933d452a9db52d47548190227"
      url "https://github.com/oullin/fmtkit/releases/download/v#{version}/fmtkit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1e1874f71ea4261eb03611d0bba559be016d2716b0e2a4014178848a7479ccd"
      url "https://github.com/oullin/fmtkit/releases/download/v#{version}/fmtkit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fmtkit"
  desc "TS/Vue and Go formatting pipeline in a single self-contained binary"
  homepage "https://github.com/oullin/fmtkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fmtkit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fmtkit"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The TS/Vue toolchain (oxfmt, oxlint, oxc-parser) is embedded in the
    binary and extracted to your user cache directory on first run; no
    Node.js installation is required.
  EOS
end
