# This file was generated by GoReleaser. DO NOT EDIT.
cask "fmtkit" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "d8b1583dad4499119e7b0f96b6e1021eb8892af6ec99ff4e4072faa6640121a0"
      url "https://github.com/oullin/fmtkit/releases/download/v#{version}/fmtkit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fc4160c7f93d2dc6ea9ad22cb11acd15a0f148b691af9d9739d27aeb23ec5fc9"
      url "https://github.com/oullin/fmtkit/releases/download/v#{version}/fmtkit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9fe28d109485f80aaba61185ef039d737c336475e36c34450fdf7d0654ffcb19"
      url "https://github.com/oullin/fmtkit/releases/download/v#{version}/fmtkit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "07366af210303e5620fb32f047636c6f9f18c787b060e02b31bc8710714c629f"
      url "https://github.com/oullin/fmtkit/releases/download/v#{version}/fmtkit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fmtkit"
  desc "TS/Vue and Go formatting pipeline in a single self-contained binary"
  homepage "https://github.com/oullin/fmtkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fmtkit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fmtkit"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The TS/Vue toolchain (oxfmt, oxlint, oxc-parser) is embedded in the
    binary and extracted to your user cache directory on first run; no
    Node.js installation is required.
  EOS
end
