# This file was generated by GoReleaser. DO NOT EDIT.
cask "fmtkit" do
  version "0.13.1"

  on_macos do
    on_arm do
      sha256 "d187fe897da290246dfb4260c7dad508e288e6f020343549e2628249bb85f3fc"
      url "https://github.com/oullin/fmtkit/releases/download/v#{version}/fmtkit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "310e984d5d2bbf753fac3f4a3ee1af937f8ac26dfdd8a50e3a48d450af24be3f"
      url "https://github.com/oullin/fmtkit/releases/download/v#{version}/fmtkit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "88c626c841fd92dcdeaeacdefdced227c2c15a6ff478620e11ac205d4ae44018"
      url "https://github.com/oullin/fmtkit/releases/download/v#{version}/fmtkit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cf0fe98d85b5e33cc13d4ff9b2447e63294413e91746235e84d3bd72c611c3ef"
      url "https://github.com/oullin/fmtkit/releases/download/v#{version}/fmtkit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fmtkit"
  desc "TS/Vue and Go formatting pipeline in a single self-contained binary"
  homepage "https://github.com/oullin/fmtkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fmtkit"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/fmtkit"], must_succeed: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The TS/Vue toolchain (oxfmt, oxlint, oxc-parser) is embedded in the
    binary and extracted to your user cache directory on first run; no
    Node.js installation is required.
  EOS
end
